import os.path


tests_directory = './tests/'
test_sources = Glob('./*.cpp') + Glob(tests_directory + '*.cpp')

cpp_include_path = ['../include/', '../lib/Catch2/single_include']

env = Environment(CPPPATH=cpp_include_path)
env.Append(CXXFLAGS='-std=c++98')

test_executable = env.Program(target='run-tests', source=test_sources)

env.Alias('check', test_executable, './$SOURCE')


# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4 filetype=python
#
