language: cpp
sudo: false
addons:
    apt:
        packages:
            - lcov
python:
  - "3.6.4"
before_install:
  - which "python"
  - python -c "import sys; print sys.path"
before_script:
  - scons --version
script:
  - cd test
  - scons check
  - ./generate-coverage-report.sh
