language: cpp
sudo: false
addons:
    apt:
        packages:
            - lcov
python:
  - "3.6.4"
before_install:
  - which "python"
  - python -c "import sys; print sys.path"
  - pip install --user codecov
script:
  - cd test
  - scons check
  - lcov --capture --no-external --directory . --output-file coverage.info
after_success:
  - codecov

