language: cpp
sudo: false
addons:
    apt:
        packages:
            - lcov
python:
  - "3.6.4"
before_install:
  - which "python"
  - python -c "import sys; print sys.path"
  - pip install --user cpp-coveralls
script:
  - cd test
  - scons check
  - ./generate-coverage-report.sh
after_success:
  - coveralls --exclude lib --gcov-options '\-lp'

